// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPeer(arg1) {
  return window['go']['main']['App']['AddPeer'](arg1);
}

export function ForgetPeer(arg1) {
  return window['go']['main']['App']['ForgetPeer'](arg1);
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function Peers() {
  return window['go']['main']['App']['Peers']();
}

export function Scan() {
  return window['go']['main']['App']['Scan']();
}

export function Self() {
  return window['go']['main']['App']['Self']();
}

export function SendText(arg1, arg2) {
  return window['go']['main']['App']['SendText'](arg1, arg2);
}

export function SetName(arg1) {
  return window['go']['main']['App']['SetName'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
