// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {node} from '../models';
import {main} from '../models';
import {discovery} from '../models';
import {proto} from '../models';

export function AddPeer(arg1:string):Promise<node.Peer>;

export function AllowSunshineFirewall():Promise<void>;

export function AnswerPair(arg1:string,arg2:boolean):Promise<void>;

export function Background():Promise<main.BackgroundSettings>;

export function CancelControl(arg1:string):Promise<void>;

export function CancelPair(arg1:string):Promise<void>;

export function CancelTransfer(arg1:number):Promise<void>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ChooseReceiveDir():Promise<string>;

export function ClearHistory(arg1:string):Promise<void>;

export function ClipboardStatus():Promise<node.ClipboardStatus>;

export function ControlInfo(arg1:string):Promise<node.ControlInfo>;

export function FindOnNetwork():Promise<Array<node.Peer>>;

export function Fingerprint():Promise<string>;

export function FirewallStatus():Promise<main.FirewallStatus>;

export function FixFirewall():Promise<void>;

export function ForgetPeer(arg1:string):Promise<void>;

export function History():Promise<Array<node.Message>>;

export function HostInfo():Promise<node.HostInfo>;

export function InstallProgram(arg1:string):Promise<void>;

export function InstallUpdate():Promise<void>;

export function LocalAddrs():Promise<Array<discovery.LocalAddr>>;

export function MakeNetworkPrivate():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenSunshineSetup():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Peers():Promise<Array<node.Peer>>;

export function PendingPairs():Promise<Array<node.PairRequest>>;

export function PickFiles(arg1:string):Promise<void>;

export function PickFolder(arg1:string):Promise<void>;

export function ReceiveDir():Promise<string>;

export function RetryTransfer(arg1:number):Promise<void>;

export function RevealPath(arg1:string):Promise<void>;

export function Scan():Promise<void>;

export function Self():Promise<proto.Device>;

export function SendPasted(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendPaths(arg1:string,arg2:Array<string>):Promise<void>;

export function SendText(arg1:string,arg2:string):Promise<void>;

export function SetAppMenu(arg1:boolean):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetClipboardSync(arg1:boolean):Promise<void>;

export function SetKeepInTray(arg1:boolean):Promise<void>;

export function SetName(arg1:string):Promise<void>;

export function SetSunshineLogin(arg1:string,arg2:string):Promise<void>;

export function StartControl(arg1:string,arg2:node.ControlOptions):Promise<void>;

export function StartPair(arg1:string):Promise<string>;

export function Status():Promise<string>;

export function Unpair(arg1:string):Promise<void>;

export function Version():Promise<string>;
