// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPeer(arg1) {
  return window['go']['main']['App']['AddPeer'](arg1);
}

export function AnswerPair(arg1, arg2) {
  return window['go']['main']['App']['AnswerPair'](arg1, arg2);
}

export function CancelPair(arg1) {
  return window['go']['main']['App']['CancelPair'](arg1);
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ChooseReceiveDir() {
  return window['go']['main']['App']['ChooseReceiveDir']();
}

export function FindOnNetwork() {
  return window['go']['main']['App']['FindOnNetwork']();
}

export function Fingerprint() {
  return window['go']['main']['App']['Fingerprint']();
}

export function ForgetPeer(arg1) {
  return window['go']['main']['App']['ForgetPeer'](arg1);
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function LocalAddrs() {
  return window['go']['main']['App']['LocalAddrs']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function Peers() {
  return window['go']['main']['App']['Peers']();
}

export function PendingPairs() {
  return window['go']['main']['App']['PendingPairs']();
}

export function PickFiles(arg1) {
  return window['go']['main']['App']['PickFiles'](arg1);
}

export function ReceiveDir() {
  return window['go']['main']['App']['ReceiveDir']();
}

export function RetryTransfer(arg1) {
  return window['go']['main']['App']['RetryTransfer'](arg1);
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function Scan() {
  return window['go']['main']['App']['Scan']();
}

export function Self() {
  return window['go']['main']['App']['Self']();
}

export function SendPasted(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPasted'](arg1, arg2, arg3);
}

export function SendPaths(arg1, arg2) {
  return window['go']['main']['App']['SendPaths'](arg1, arg2);
}

export function SendText(arg1, arg2) {
  return window['go']['main']['App']['SendText'](arg1, arg2);
}

export function SetName(arg1) {
  return window['go']['main']['App']['SetName'](arg1);
}

export function StartPair(arg1) {
  return window['go']['main']['App']['StartPair'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Unpair(arg1) {
  return window['go']['main']['App']['Unpair'](arg1);
}
